
networks:
  minutas-net:
    driver: bridge

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_BLOCK_SSRF_GET_ADDITIONAL_HOSTS=ollama,host.docker.internal
      - N8N_BLOCK_SSRF_POST_ADDITIONAL_HOSTS=ollama,host.docker.internal
    volumes:
      - minutas_n8n_data:/home/node/.n8n
    networks:
      - minutas-net
    restart: unless-stopped


  frontend_ui:
    build: ./frontend_ui
    container_name: frontend_ui
    ports:
      - "8505:8501"
    environment:
      - N8N_BASE_URL=http://n8n:5678
    volumes:
      - ./frontend_ui:/app
    depends_on:
      - n8n
    networks:
      - minutas-net
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=1m
    volumes:
      - minutas_ollama_data:/root/.ollama
    networks:
      - minutas-net
    restart: unless-stopped

volumes:
  minutas_n8n_data:
  minutas_ollama_data: